name: otw-dev
channels:
  - conda-forge
dependencies:
    # Base
  - python=3.10
    # Webserver
  - uvicorn=0.17.6
  - fastapi=0.78.0
    # Testing
  - requests=2.27.1
  - pytest=7.1.2
    # Style
  - black=22.3.0