line-length = 100

# Always autofix, but never try to fix `F401` (unused imports).
fix = true

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["E402"]